-- BĐS RE OLTP P4 — project accounting cash flow (PG-primary)
BEGIN;

CREATE TABLE IF NOT EXISTS crm_re_project_cash_flow_lines (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
    flow_type       TEXT NOT NULL DEFAULT 'outflow',
    category        TEXT NOT NULL DEFAULT 'other',
    sub_category    TEXT NOT NULL DEFAULT '',
    line_item       TEXT NOT NULL DEFAULT '',
    amount_vnd      BIGINT NOT NULL DEFAULT 0,
    period_month    TEXT NOT NULL DEFAULT '',
    transaction_date TEXT NOT NULL DEFAULT '',
    due_date        TEXT NOT NULL DEFAULT '',
    paid_date       TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'planned',
    source_type     TEXT NOT NULL DEFAULT 'manual',
    source_ref      TEXT NOT NULL DEFAULT '',
    counterparty    TEXT NOT NULL DEFAULT '',
    notes           TEXT NOT NULL DEFAULT '',
    created_by      TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_re_cash_flow_project
    ON crm_re_project_cash_flow_lines (project_id, period_month, status);

CREATE INDEX IF NOT EXISTS idx_crm_re_cash_flow_category
    ON crm_re_project_cash_flow_lines (project_id, category, flow_type);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_re_cash_flow_source_ref
    ON crm_re_project_cash_flow_lines (project_id, source_ref)
    WHERE trim(source_ref) <> '';

COMMIT;
