-- BĐS RE OLTP P2 — lead config, project staff, marketing ingest (PG-primary)
BEGIN;

CREATE TABLE IF NOT EXISTS crm_re_project_lead_config (
  project_id INTEGER PRIMARY KEY REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  webhook_slug TEXT NOT NULL DEFAULT '',
  webhook_verify_token TEXT NOT NULL DEFAULT '',
  facebook_page_id TEXT NOT NULL DEFAULT '',
  meta_ad_account_id TEXT NOT NULL DEFAULT '',
  zalo_oa_id TEXT NOT NULL DEFAULT '',
  auto_assign BOOLEAN NOT NULL DEFAULT TRUE,
  webhook_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_re_lead_config_slug
  ON crm_re_project_lead_config (lower(trim(webhook_slug)))
  WHERE trim(webhook_slug) <> '';

CREATE TABLE IF NOT EXISTS crm_re_project_facebook_forms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  page_id TEXT NOT NULL DEFAULT '',
  form_id TEXT NOT NULL UNIQUE,
  form_name TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS crm_re_project_zalo_campaigns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  oa_id TEXT NOT NULL DEFAULT '',
  campaign_id TEXT NOT NULL UNIQUE,
  campaign_name TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS crm_re_project_website_routes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  route_key TEXT NOT NULL UNIQUE,
  route_name TEXT NOT NULL DEFAULT '',
  route_type TEXT NOT NULL DEFAULT 'utm',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS crm_re_project_staff (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  staff_id BIGINT NOT NULL,
  role TEXT NOT NULL DEFAULT 'sales',
  assign_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  scope_product_lines JSONB NOT NULL DEFAULT '[]'::jsonb,
  scope_zones JSONB NOT NULL DEFAULT '[]'::jsonb,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  left_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (project_id, staff_id)
);

CREATE INDEX IF NOT EXISTS idx_crm_re_project_staff_active
  ON crm_re_project_staff (project_id)
  WHERE left_at IS NULL;

COMMIT;
