-- Zero SQLite Wave 0 — dual-module straggler
BEGIN;

CREATE TABLE IF NOT EXISTS crm_lifecycle_finance_confirm (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lifecycle_id    INTEGER NOT NULL,
    staff_id        INTEGER,
    staff_email     TEXT NOT NULL DEFAULT '',
    outstanding_vnd BIGINT NOT NULL DEFAULT 0,
    ar_pending_vnd  BIGINT NOT NULL DEFAULT 0,
    ar_overdue_vnd  BIGINT NOT NULL DEFAULT 0,
    strict_mode     BOOLEAN NOT NULL DEFAULT FALSE,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_lifecycle_finance_confirm_lc
    ON crm_lifecycle_finance_confirm (lifecycle_id, created_at DESC);

COMMIT;
