-- BĐS RE OLTP P3 — KPI, risks, budget lines + buyer lead re_project_id (PG-primary)
BEGIN;

CREATE TABLE IF NOT EXISTS crm_re_project_kpis (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
    category        TEXT NOT NULL DEFAULT 'sales',
    metric_name     TEXT NOT NULL,
    target_value    NUMERIC(18, 4) NOT NULL DEFAULT 0,
    actual_value    NUMERIC(18, 4) NOT NULL DEFAULT 0,
    unit            TEXT NOT NULL DEFAULT '',
    period_month    TEXT NOT NULL DEFAULT '',
    weight_pct      NUMERIC(8, 2) NOT NULL DEFAULT 0,
    owner_name      TEXT NOT NULL DEFAULT '',
    owner_staff_id  BIGINT,
    track_status    TEXT NOT NULL DEFAULT 'active',
    metric_code     TEXT NOT NULL DEFAULT '',
    metric_id       BIGINT,
    staff_kpi_id    BIGINT,
    notes           TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_re_project_kpis_project
    ON crm_re_project_kpis (project_id, period_month DESC, owner_staff_id, id);

CREATE TABLE IF NOT EXISTS crm_re_project_risks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
    category        TEXT NOT NULL DEFAULT 'market',
    title           TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    probability_pct NUMERIC(8, 2) NOT NULL DEFAULT 0,
    impact_pct      NUMERIC(8, 2) NOT NULL DEFAULT 0,
    risk_level      TEXT NOT NULL DEFAULT 'medium',
    mitigation      TEXT NOT NULL DEFAULT '',
    owner_name      TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'open',
    due_date        TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_re_project_risks_project
    ON crm_re_project_risks (project_id, risk_level DESC, id);

CREATE TABLE IF NOT EXISTS crm_re_project_budget_lines (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
    category        TEXT NOT NULL DEFAULT 'revenue',
    line_item       TEXT NOT NULL,
    period_month    TEXT NOT NULL DEFAULT '',
    planned_vnd     BIGINT NOT NULL DEFAULT 0,
    actual_vnd      BIGINT NOT NULL DEFAULT 0,
    notes           TEXT NOT NULL DEFAULT '',
    sub_category    TEXT NOT NULL DEFAULT '',
    source_type     TEXT NOT NULL DEFAULT 'manual',
    source_ref      TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_re_budget_project
    ON crm_re_project_budget_lines (project_id, period_month, category, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_crm_re_budget_source_ref
    ON crm_re_project_budget_lines (project_id, source_ref)
    WHERE trim(source_ref) <> '';

-- Buyer leads: denormalized project link for BĐS pack OLTP
ALTER TABLE crm_leads
    ADD COLUMN IF NOT EXISTS re_project_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_crm_leads_re_project
    ON crm_leads (re_project_id)
    WHERE re_project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_crm_leads_re_buyer_flow
    ON crm_leads (re_project_id, created_at DESC)
    WHERE (meta_json ->> 'lead_flow_kind') = 're_buyer';

COMMIT;
