-- Pack BĐS P3 — Apply: scripts/apply_pg_ddl_bds_p3.sh
BEGIN;

ALTER TABLE bds_launch_phases ADD COLUMN IF NOT EXISTS policy_id UUID;
ALTER TABLE bds_launch_phases ADD COLUMN IF NOT EXISTS price_list_id INTEGER;

CREATE TABLE IF NOT EXISTS bds_sales_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES bds_tenants (id),
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'archived')),
  audience TEXT NOT NULL DEFAULT 'all'
    CHECK (audience IN ('direct', 'broker', 'all')),
  effective_from TIMESTAMPTZ,
  effective_to TIMESTAMPTZ,
  discount_cap_pct NUMERIC NOT NULL DEFAULT 0,
  hold_ttl_minutes INTEGER,
  deposit_min_vnd BIGINT NOT NULL DEFAULT 0,
  vbtt_min_paid_pct NUMERIC NOT NULL DEFAULT 0,
  hdmb_min_paid_pct NUMERIC NOT NULL DEFAULT 30,
  payment_template_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  vat_mode TEXT NOT NULL DEFAULT 'included'
    CHECK (vat_mode IN ('included', 'excluded')),
  maintenance_fee_vnd BIGINT NOT NULL DEFAULT 0,
  fee_unit TEXT NOT NULL DEFAULT 'per_unit'
    CHECK (fee_unit IN ('per_unit', 'per_m2')),
  rules_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  activated_by TEXT NOT NULL DEFAULT '',
  activated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bds_policies_project_code
  ON bds_sales_policies (project_id, lower(trim(code)));

CREATE UNIQUE INDEX IF NOT EXISTS uq_bds_policies_one_active_audience
  ON bds_sales_policies (project_id, audience)
  WHERE status = 'active';

CREATE TABLE IF NOT EXISTS crm_re_price_lists (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES crm_re_projects (id) ON DELETE CASCADE,
  tenant_id UUID REFERENCES bds_tenants (id),
  policy_id UUID REFERENCES bds_sales_policies (id),
  version_code TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  effective_date TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'archived')),
  notes TEXT NOT NULL DEFAULT '',
  applied_at TEXT NOT NULL DEFAULT '',
  applied_by TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE crm_re_price_lists ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES bds_tenants (id);
ALTER TABLE crm_re_price_lists ADD COLUMN IF NOT EXISTS policy_id UUID;

CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_re_price_lists_version
  ON crm_re_price_lists (project_id, lower(trim(version_code)))
  WHERE trim(version_code) <> '';

CREATE TABLE IF NOT EXISTS crm_re_price_list_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price_list_id INTEGER NOT NULL REFERENCES crm_re_price_lists (id) ON DELETE CASCADE,
  unit_code TEXT NOT NULL DEFAULT '',
  zone TEXT NOT NULL DEFAULT '',
  list_price_vnd BIGINT NOT NULL DEFAULT 0,
  net_price_vnd BIGINT NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_re_price_list_items_unit
  ON crm_re_price_list_items (price_list_id, lower(trim(unit_code)))
  WHERE trim(unit_code) <> '';

COMMIT;
